### PR TITLE
Optimized German cards

### PR DESCRIPTION
**Pull request by ntlrsk**
Reduced the size of two of German card files (Dance and Name)

### CODE REVIEW

**Comment by ntlrsk** [comment]
@chrisgarrity Thanks for catching that I didn't mean to include the Chinese files in the pull request - still figuring out this new process.

**Comment by chrisgarrity** [comment]
@ntlrsk do you need help updating the PR to take out the zh-tw change?

**Comment by ntlrsk** [comment]
@chrisgarrity Yes, if you can take out the zh-tw then it's good to go - thanks for your help.

**Comment by chrisgarrity** [comment]
Closing this PR in favor of https://github.com/LLK/scratch-resources/pull/26 without the zh-tw change

**Pull request closed without merging**
